#!/bin/sh

log=$(mktemp /tmp/wmas-openbox-XXXXXXXX.txt)
echo "Openbox autostart file" > $log
echo -e "Executed @ $(date)\n" >> $log

hsetroot -cover ~/.dotfiles/assets/wallpapers/current >> $log 2>&1
xcompmgr >> $log 2>&1 &
soteria >> $log 2>&1 &

# dumb yambar workaround https://codeberg.org/dnkl/yambar/issues/429
xterm -geometry 1x1+0+18 >> $log 2>&1 &
temp=$!
sleep 1
yambar >> $log 2>&1 &
sleep 1
kill $temp
