name: homepage
services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        ports:
            - 3000:3000
        volumes:
            - /etc/homepage-dashboard:/app/config # Make sure your local config directory exists
            - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
            - /home/rae/.dotfiles/assets/wallpapers:/app/public/images
